
default:
  image: node:15.5.1

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint

build-proto:
  stage: build
  image: juanjodiaz/grpc-web-generator:1.2.1
  cache: {}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ./build_grpc-web-client.sh
  artifacts:
    paths:
      - ./grpc-api-client
    untracked: false
    expire_in: 7 days

typecheck:
  stage: lint
  script:
    - npm install
    - npm run typecheck
lint:
  stage: lint
  script:
    - npm install
    - npm run lint

formatcheck:
  stage: lint
  script:
    - npm install
    - npm run formatcheck

build:
  stage: lint
  script:
  - npm install
  - npm run build

