# This file only contains services meant for developing and testing the node-dashboard.
version: '3'
services:

  # Envoy proxy for developing locally.
  # IMPORTANT: Attaches directly to host network and ports, this is nescessary for the
  # container to reach a node running on the host.
  grpc-proxy:
    image: envoyproxy/envoy:v1.18.3
    network_mode: "host"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml

  # Container with grpc-web build tools, and a script for building.
  # This is only ment as a convenient way to build the GRPC-web typescript files.
  build-grpc:
    image: juanjodiaz/grpc-web-generator
    volumes:
      - ./deps/grpc-api:/deps/grpc-api:ro
      - ./build_grpc-web-client.sh:/build_grpc-web-client.sh:ro
      - ./grpc-api-client:/grpc-api-client
    command: bash /build_grpc-web-client.sh

  # A service to quickly spin up an nginx service with the nginx config, meant for testing changes.
  # Serves files from the dist directory created when building the node-dashboard.
  # IMPORTANT: Attaches directly to host network and ports.
  nginx-test:
    image: nginx:1.18.0
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/node-dashboard.conf
      - ./dist:/node-dashboard/static:ro
