
version: '3'
services:
  grpc-proxy:
    image: envoyproxy/envoy:v1.16.1
    network_mode: "host"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
